# Generated by Django 5.2.5 on 2025-08-21 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'txt'])])),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('analysis_timestamp', models.DateTimeField(auto_now=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('ats_score', models.FloatField(blank=True, null=True)),
                ('analysis_results', models.JSONField(blank=True, default=dict)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_match_score', models.FloatField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Resume Analysis',
                'verbose_name_plural': 'Resume Analyses',
                'ordering': ['-upload_timestamp'],
            },
        ),
    ]
